### ISSUE TITLE
Chinese fans

### ISSUE THREAD

**Issue by xuanS1000RR** [2010kohtep/h1-valve-reports#1]
I have used Project3 -2010 Kohtep. work on CS1.6 very well. Is there a program that attacks the Source engine server?

**Comment by kohtep** [comment]
Good to know! Unfortunately, I can’t say something about Source Engine, since I almost didn't work on this and didn't try to find problems in it.

**Comment by xuanS1000RR** [comment]
okay, but thank you for your HL engine attack software. It helped me punish some servers for misbehaving
